server:
  port: 8080
sa-token:
  # jwt秘钥
  jwt-secret-key: 碧蓝小新星(*^▽^*)
spring:
  application:
    name: dingding-gateway
  cloud:
    nacos:
      server-addr: 8.217.8.255:8848
    gateway:
      routes: #路由规则
        - id: user
          uri: lb://dingding-user
          predicates:
            - Path=/user/**
auth:
  exclude-paths:
    - /user/login
    - /user/register
    - /book/page
