server:
  port: 8080
spring:
  application:
    name: dingding-gateway
  cloud:
    nacos:
      server-addr: 8.217.8.255:8848
    gateway:
      routes: #路由规则
        - id: user
          uri: lb://dingding-user
          predicates:
            - Path=/user/**

